name: 'resource_utilization'
version: '1.0.0'
config-version: 2

profile: 'resource_utilization'

# File paths
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# =============================================================================
# Model configurations
# =============================================================================
# Schema naming follows dbt standard convention:
#   base schema (profiles.yml) + folder name = final schema
#
#   dev:  dbt_dev  + staging_silver → dbt_dev_staging_silver
#         dbt_dev  + intermediate_silver → dbt_dev_intermediate_silver
#         dbt_dev  + mart_gold           → dbt_dev_mart_gold
#   seeds land in dbt_dev_staging_silver alongside staging views
#
#   prod: dbt_prod + staging_silver → dbt_prod_staging_silver
#         dbt_prod + intermediate_silver → dbt_prod_intermediate_silver
#         dbt_prod + mart_gold           → dbt_prod_mart_gold
# =============================================================================

models:
  resource_utilization:

    staging:
      +materialized: view
      +schema: staging_silver

    intermediate:
      +materialized: table
      +schema: intermediate_silver

    marts:
      +materialized: table
      +schema: mart_gold

seeds:
  resource_utilization:
    +schema: seeds
    +quote_columns: false
